DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    SET TIME ZONE -03:00
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIME,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);